name: Python CI Pipeline

# Запускается при каждом push в репозиторий
on: [push]

jobs:
  python-tests:
    name: Run Python Tests
    runs-on: ubuntu-latest
    
    steps:
    # Шаг 1: Получить код из репозитория
    - name: Checkout repository
      uses: actions/checkout@v4

    # Шаг 2: Настроить Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Шаг 3: Запуск Unit-тестов
    - name: Run Unit Tests
      run: |
        echo "=== ЗАПУСК UNIT-ТЕСТОВ ==="
        python3 test_unit.py

    # Шаг 4: Запуск Интеграционных тестов
    - name: Run Integration Tests
      run: |
        echo "=== ЗАПУСК ИНТЕГРАЦИОННЫХ ТЕСТОВ ==="
        python3 test_integration.py

    # Шаг 5: Запуск всех тестов
    - name: Run All Tests
      run: |
        echo "=== ЗАПУСК ВСЕХ ТЕСТОВ ==="
        python3 run_tests.py

    # Шаг 6: Успешное завершение
    - name: Success Message
      run: |
        echo "========================================"
        echo "✅ ВЫ МОЛОДЕЦ! ВСЕ ТЕСТЫ ПРОЙДЕНЫ!"
        echo "========================================"
        echo "Python тестирование завершено успешно"
        echo "Ветка: ${GITHUB_REF##*/}"
        echo "========================================"
